<?php

namespace App\Models;

use App\Traits\UtilsTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ExpenseSettings extends Model
{
    use HasFactory,
        SoftDeletes,
        UtilsTrait;

    /**
     * @var array
     */
    protected $fillable = [
        'title',
        'userId',
        'categoryId',
        'amount',
        'isMonthly',
    ];

    /**
     *
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        parent::saving(function ($row) {
            $row->amount = $row->floatToInt($row->amount);
        });
    }

    /**
     * @param $filters
     * @param $query
     */
    public function scopeFilterBy($query, $filters)
    {
        return $query->orderBy('id', 'DESC');
    }

    /**
     * Get user
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function user()
    {
        return $this->belongsTo(Client::class, 'userId', 'id');
    }
}
